[server]
port = 8503
enableXsrfProtection = true
maxUploadSize = 200
enableCORS = true
headless = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "error"

[browser]
gatherUsageStats = false
